export const FETCH_LOCATION = 'FETCH_LOCATION';
export const DISABLE_LOCATION = 'DISABLE_LOCATION';
export const FETCH_USER = 'FETCH_USER';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const UPDATE_FILTER_LOCATION = 'UPDATE_FILTER_LOCATION';
